# Generated by Django 3.0.8 on 2022-04-10 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dete',
            new_name='pub_date',
        ),
    ]
